name: mbw204_club_ina
description: Community App.

publish_to: 'none'

version: 1.0.0+12

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_downloader:
   git:
      url: https://github.com/fluttercommunity/flutter_downloader.git
      ref: embedding-v2

  # A
  auto_size_text: ^2.1.0

  # B
  better_player: ^0.0.61
  bubble_tab_indicator: ^0.1.4
  badges: ^2.0.1

  # C
  cupertino_icons: ^1.0.0
  carousel_slider: ^2.3.1
  cached_network_image: ^2.2.0+1
  connectivity: ^3.0.4
  chewie: ^0.12.2
  circular_check_box: ^1.0.0

  # D
  dropdown_search: ^0.6.1
  dropdown_formfield: ^0.1.3

  # E
  ext_storage: ^1.0.3

  # F
  flutter_switch: ^0.3.1
  file_picker: ^2.1.6
  flutter_html: ^1.0.0
  flappy_search_bar: ^1.7.2
  flutter_picker: ^2.0.1
  flutter_pdfview: ^1.1.0
  flutter_svg:
  flutter_cache_manager: ^2.1.2
  firebase_messaging: ^7.0.3
  flutter_native_image: ^0.0.5
  fluttertoast: ^8.0.7
  flutter_link_preview: ^1.5.6
  flushbar: ^1.5.0
  flutter_animated_dialog: ^2.0.0
  flutter_rating_bar: ^4.0.0
  fancy_bottom_navigation: ^0.3.2
  flutter_local_notifications: ^4.0.1+2
  flutter_mobx: ^1.1.0+2
  filesize: ^2.0.1
  flutter_webview_plugin: ^0.4.0
  # flutter_staggered_grid_view: ^0.3.2
  flutter_absolute_path: ^1.0.6
  flutter_launcher_icons: ^0.9.0

  # G
  get_it: ^7.1.3
  geolocator: ^6.2.1
  geocoding: ^1.0.5
  google_maps_flutter: ^1.2.0
  google_maps_place_picker: ^1.0.1

  # I
  icon_shadow: ^1.0.1

  # J
  jwt_decoder: ^2.0.1

  # P
  provider: ^4.3.2+2
  page_transition: ^2.0.2
  photo_view: ^0.11.1
  progress_dialog: ^1.2.1
  permission_handler: ^5.0.1+1
  package_info: ^2.0.1

  # D
  dio: ^3.0.10
  date_time_picker: ^2.0.0

  # L
  lottie: ^1.0.1

  # T
  timeago: ^3.0.2
  table_calendar: ^2.3.3
  timeline_list: ^0.0.5
  timelines: ^0.1.0

  # R
  readmore: ^2.0.0

  # M
  multi_image_picker: ^4.7.15
  modal_bottom_sheet: ^2.0.0

  # N
  native_contact_picker: ^0.0.6

  # H
  hex: ^0.2.0

  # I
  image_picker: ^0.6.7+12

  # Q 
  qr_flutter: ^4.0.0

  # U
  url_launcher: ^5.7.4

  # S
  shared_preferences: ^0.5.12
  shimmer: ^2.0.0
  share: ^2.0.2
  slide_to_confirm: ^0.0.7
  socket_io_client: ^1.0.1
  sizer: ^2.0.13
  sqflite: ^2.0.0+3

  # V
  video_player: ^1.0.1

  # W
  webview_flutter: ^1.0.7
 

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo-home-menu.png"

flutter:

  uses-material-design: true

  assets:
  - assets/images/
  - assets/images/svg/
  - assets/icons/
  - assets/language/
  - assets/lottie/
  - assets/pdf/

  fonts:
    - family: Poppins
      fonts: 
      - asset: assets/fonts/poppins/Poppins-Regular.ttf
      - asset: assets/fonts/poppins/Poppins-Italic.ttf
      - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/titillium/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-Italic.ttf
        - asset: assets/fonts/titillium/TitilliumWeb-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/titillium/TitilliumWeb-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700